export const hicheel = [
  {
    id: 1,
    name: 'Togtmol_Guidel',
    title: 'Тогтмол гүйдэл (Цахилгаан хэлхээ)',
    videoSrc: 'https://www.youtube.com/embed/P5dw1abNQ5k?si=sE4p3sHgOQSkZTDx',
  },
  {
    id: 2,
    name: 'Biyiin_Naygt',
    title: 'Биеийн нягт',
    videoSrc: 'https://www.youtube.com/embed/hCJKwHLeGRQ?si=LC7yO4Z7kIrfmU2M',
  },
  {
    id: 3,
    name: 'Ternodinamic',
    title: 'Термодинамик Хийн хуулиуд',
    videoSrc: 'https://www.youtube.com/embed/YhkzEZm--zQ',
  },
  {
    id: 4,
    name: 'Eyesh23-2-1',
    title: 'Физик ЭЕШ 2023 оны 2.1 даалгавар',
    videoSrc: 'https://www.youtube.com/embed/WOeck4uKJBc?si=1OuPaTaPAdzMWVPv',
  },
  {
    id: 5,
    name: 'OUSHB',
    title: 'Өнцөг үүсгэн шидсэн бие',
    videoSrc: 'https://www.youtube.com/embed/Gsa6X01Kduo?si=m0usmtLl1Bd4ohwN',
  },
  {
    id: 6,
    name: 'Eyesh24-2-2-3',
    title: 'Физик эеш 2024 2.2 2.3',
    videoSrc: 'https://www.youtube.com/embed/7fm3AOGFAxM?si=0Q9hXIxYdp4ZThyY',
  },
  {
    id: 7,
    name: 'Eyesh24A-1-21',
    title: 'ЭЕШ Физик 2024 он 1-21 А Хувилбар',
    videoSrc: 'https://www.youtube.com/embed/OqFvYCP3S2c?si=SoyX65Ch-LmTgX8X',
  },
  {
    id: 8,
    name: 'Eyesh24A-22-24',
    title: 'Физик 2024 А Хувилбар 22-46',
    videoSrc: 'https://www.youtube.com/embed/zomSjjARpHs?si=Jrj8d04zn-akNDcP',
  },
  {
    id: 9,
    name: 'Eyesh23B-1-19',
    title: '2023 Физик ЭЕШ Хувилбар B 1-19',
    videoSrc: 'https://www.youtube.com/embed/N6Z6Rn85-7k?si=hf2mqaEw5m4S8FOn',
  },
  {
    id: 10,
    name: 'Eyesh23B-20-46',
    title: '2023 Физик ЭЕШ Хувилбар В 20-46',
    videoSrc: '',
  },
  {
    id: 11,
    name: 'Eyesh22B-1-10',
    title: '2022 оны Физик ЭЕШ 1-10 ',
    videoSrc: 'https://www.youtube.com/embed/3UPV9LDJOcU?si=AoGdJFGa5Io1vHL7',
  },
  {
    id: 12,
    name: 'Eyesh22B-11-21',
    title: '2022 он Физик эеш 11-21',
    videoSrc: 'https://www.youtube.com/embed/RGD502zmklc?si=NjKBSq_FqEcu2d6m',
  },
  {
    id: 13,
    name: 'Eyesh22B-22-46',
    title: 'Физик ЭЕШ 2022 B Хувилбар 22-46',
    videoSrc: 'https://www.youtube.com/embed/YVW6VcwNbjs?si=rPXyNqKQQSiBdZ9Q',
  },
  {
    id: 14,
    name: 'Toli',
    title: 'Толь',
    videoSrc: 'https://www.youtube.com/embed/qYBHf4GZ5oQ?si=rBCxz5tbNmlOpnyu',
  },
  {
    id: 15,
    name: 'Eyesh24D-1-21',
    title: 'Физик ЭЕШ 2024 он D 1-21',
    videoSrc: 'https://www.youtube.com/embed/A-EbhfPb8qY?si=_qyRbvyCKm9mqUwY',
  },
  {
    id: 16,
    name: 'Linz',
    title: 'Линз - Хүний нүд',
    videoSrc: 'https://www.youtube.com/embed/e0d3-wX8cwM?si=g_cMKa8GDeF3-t_g',
  },
  {
    id: 17,
    name: 'Eyesh24A',
    title: 'Физик - Улсын шалгалт 2024 он',
    videoSrc: 'https://www.youtube.com/embed/1GK2RxNm7KA?si=9RG8GxSbq6u9_KNk',
  },
  {
    id: 18,
    name: 'MathEyesh24D',
    title: 'Математик ЭЕШ 2024 задгай даалгавар D хувилбар',
    videoSrc: 'https://www.youtube.com/embed/zaef47k3SG8?si=C5QAg38q0CmvslUI',
  },
  {
    id: 19,
    name: 'Eyesh24A-2-1-4',
    title: '2024 оны Улсын шалгалт задгай даалгавар',
    videoSrc: 'https://www.youtube.com/embed/A32LSL53584?si=1tbtCXaJAGm9TEi3',
  },
  {
    id: 20,
    name: 'Huvisagch',
    title: 'Хувьсагч олох',
    videoSrc: 'https://www.youtube.com/embed/UnSf3_fEc_s?si=c5pNPHc6bAyXVVnw',
  },
  {
    id: 21,
    name: 'DuuAvia',
    title: 'Дуу авиа',
    videoSrc: 'https://www.youtube.com/embed/urNwlDMqbM8?si=jCyMvux4W1HO6CbV',
  },
];
