export const items = [
  {
    id: 1,
    name:'medkui',
    title: 'Pendulum',
    subject: 'chemistry',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. ',
    img:'https://media.istockphoto.com/id/1328846821/vector/pendulum.jpg?s=612x612&w=0&k=20&c=P5xd_jxbGny6kVQbwQaKwefldtI9sIFLx04DCMOLkQY=',
    price: 19990,
    materials: [
      'String',
      'Weight ',
      'Stopwatch',
      'Protractor'
    ],
  },
  {
    id: 2,
    name:'madkui',
    title: 'Pendulum',
    subject: 'physic',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. ',
    img:'https://media.istockphoto.com/id/1328846821/vector/pendulum.jpg?s=612x612&w=0&k=20&c=P5xd_jxbGny6kVQbwQaKwefldtI9sIFLx04DCMOLkQY=',
    price: 19990,
    materials: ['String',
      'Weight',
      'Stopwatch',
      'Protractor'],
  },
  {
    id: 3,
    name:'madkui',
    title: 'Pendulum',
    subject: 'physic',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. ',
    img:'https://media.istockphoto.com/id/1328846821/vector/pendulum.jpg?s=612x612&w=0&k=20&c=P5xd_jxbGny6kVQbwQaKwefldtI9sIFLx04DCMOLkQY=',
    price: 19990,
    materials: ['String',
      'Weight',
      'Stopwatch',
      'Protractor'],
  },
  {
    id: 4,
    name:'madkui',
    title: 'Pendulum',
    subject: 'physic',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. ',
    img:'https://media.istockphoto.com/id/1328846821/vector/pendulum.jpg?s=612x612&w=0&k=20&c=P5xd_jxbGny6kVQbwQaKwefldtI9sIFLx04DCMOLkQY=',
    price: 19990,
    materials: ['String',
      'Weight',
      'Stopwatch',
      'Protractor'],
  },
  {
    id: 5,
    name:'madkui',
    title: 'Pendulum',
    subject: 'physic',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. ',
    img:'https://media.istockphoto.com/id/1328846821/vector/pendulum.jpg?s=612x612&w=0&k=20&c=P5xd_jxbGny6kVQbwQaKwefldtI9sIFLx04DCMOLkQY=',
    price: 19990,
    materials: ['String',
      'Weight',
      'Stopwatch',
      'Protractor'],
  },
  {
    id: 6,
    name:'madkui',
    title: 'Pendulum',
    subject: 'physic',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. ',
    img:'https://media.istockphoto.com/id/1328846821/vector/pendulum.jpg?s=612x612&w=0&k=20&c=P5xd_jxbGny6kVQbwQaKwefldtI9sIFLx04DCMOLkQY=',
    price: 19990,
    materials: ['String',
      'Weight',
      'Stopwatch',
      'Protractor'],
  },
  {
    id: 7,
    name:'madkui',
    title: 'Pendulum',
    subject: 'physic',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. ',
    img:'https://media.istockphoto.com/id/1328846821/vector/pendulum.jpg?s=612x612&w=0&k=20&c=P5xd_jxbGny6kVQbwQaKwefldtI9sIFLx04DCMOLkQY=',
    price: 19990,
    materials: ['String',
      'Weight',
      'Stopwatch',
      'Protractor'],
  },
  {
    id: 8,
    name:'madkui',
    title: 'Pendulum',
    subject: 'physic',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. ',
    img:'https://media.istockphoto.com/id/1328846821/vector/pendulum.jpg?s=612x612&w=0&k=20&c=P5xd_jxbGny6kVQbwQaKwefldtI9sIFLx04DCMOLkQY=',
    price: 19990,
    materials: ['String',
      'Weight',
      'Stopwatch',
      'Protractor'],
  },
]